import tensorflow as tf
import numpy as np
import statistics
from sound_feature_extract import feature_extraction

# Load the model from the HDF5 file
model_classes = [{'crickets': 0, 'helicopter': 1, 'wind': 2}, {'crickets': 0, 'helicopter': 1, 'wind': 2},
                     {'crickets': 0, 'helicopter': 1, 'wind': 2}, {'airplane': 0, 'clapping': 1},
                     {'airplane': 0, 'clapping': 1},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'dog': 0, 'door_wood_creaks': 1, 'crickets': 2, 'clock_tick': 3, 'fireworks': 4, 'hand_saw': 5,
                      'cow': 6, 'insects': 7, 'footsteps': 8, 'pig': 9, 'crackling_fire': 10, 'brushing_teeth': 11,
                      'cat': 12, 'frog': 13, 'hen': 14, 'chirping_birds': 15, 'sheep': 16, 'crow': 17, 'rooster': 18},
                     {'clock_alarm': 0, 'pouring_water': 1}, {'clock_alarm': 0, 'pouring_water': 1},
                     {'dog': 0, 'can_opening': 1, 'door_wood_creaks': 2, 'cat': 3, 'brushing_teeth': 4,
                      'drinking_sipping': 5},
                     {'dog': 0, 'can_opening': 1, 'door_wood_creaks': 2, 'cat': 3, 'brushing_teeth': 4,
                      'drinking_sipping': 5},
                     {'dog': 0, 'can_opening': 1, 'door_wood_creaks': 2, 'cat': 3, 'brushing_teeth': 4,
                      'drinking_sipping': 5},
                     {'dog': 0, 'can_opening': 1, 'door_wood_creaks': 2, 'cat': 3, 'brushing_teeth': 4,
                      'drinking_sipping': 5},
                     {'dog': 0, 'can_opening': 1, 'door_wood_creaks': 2, 'cat': 3, 'brushing_teeth': 4,
                      'drinking_sipping': 5},
                     {'dog': 0, 'can_opening': 1, 'door_wood_creaks': 2, 'cat': 3, 'brushing_teeth': 4,
                      'drinking_sipping': 5},
                     {'door_wood_creaks': 0, 'vacuum_cleaner': 1, 'clock_tick': 2, 'drinking_sipping': 3,
                      'washing_machine': 4},
                     {'door_wood_creaks': 0, 'vacuum_cleaner': 1, 'clock_tick': 2, 'drinking_sipping': 3,
                      'washing_machine': 4},
                     {'door_wood_creaks': 0, 'vacuum_cleaner': 1, 'clock_tick': 2, 'drinking_sipping': 3,
                      'washing_machine': 4},
                     {'door_wood_creaks': 0, 'vacuum_cleaner': 1, 'clock_tick': 2, 'drinking_sipping': 3,
                      'washing_machine': 4},
                     {'door_wood_creaks': 0, 'vacuum_cleaner': 1, 'clock_tick': 2, 'drinking_sipping': 3,
                      'washing_machine': 4}, {'washing_machine': 0, 'church_bells': 1},
                     {'washing_machine': 0, 'church_bells': 1},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'clock_tick': 2, 'mouse_click': 3, 'sneezing': 4,
                      'cow': 5, 'clapping': 6, 'insects': 7, 'train': 8, 'pig': 9, 'crackling_fire': 10, 'cat': 11,
                      'frog': 12, 'laughing': 13, 'door_wood_knock': 14, 'car_horn': 15, 'keyboard_typing': 16,
                      'sheep': 17, 'drinking_sipping': 18},
                     {'fireworks': 0, 'airplane': 1, 'vacuum_cleaner': 2, 'washing_machine': 3, 'thunderstorm': 4},
                     {'fireworks': 0, 'airplane': 1, 'vacuum_cleaner': 2, 'washing_machine': 3, 'thunderstorm': 4},
                     {'fireworks': 0, 'airplane': 1, 'vacuum_cleaner': 2, 'washing_machine': 3, 'thunderstorm': 4},
                     {'fireworks': 0, 'airplane': 1, 'vacuum_cleaner': 2, 'washing_machine': 3, 'thunderstorm': 4},
                     {'fireworks': 0, 'airplane': 1, 'vacuum_cleaner': 2, 'washing_machine': 3, 'thunderstorm': 4},
                     {'snoring': 0, 'hand_saw': 1, 'door_wood_creaks': 2, 'coughing': 3, 'drinking_sipping': 4,
                      'breathing': 5},
                     {'snoring': 0, 'hand_saw': 1, 'door_wood_creaks': 2, 'coughing': 3, 'drinking_sipping': 4,
                      'breathing': 5},
                     {'snoring': 0, 'hand_saw': 1, 'door_wood_creaks': 2, 'coughing': 3, 'drinking_sipping': 4,
                      'breathing': 5},
                     {'snoring': 0, 'hand_saw': 1, 'door_wood_creaks': 2, 'coughing': 3, 'drinking_sipping': 4,
                      'breathing': 5},
                     {'snoring': 0, 'hand_saw': 1, 'door_wood_creaks': 2, 'coughing': 3, 'drinking_sipping': 4,
                      'breathing': 5},
                     {'snoring': 0, 'hand_saw': 1, 'door_wood_creaks': 2, 'coughing': 3, 'drinking_sipping': 4,
                      'breathing': 5}, {'can_opening': 0, 'pouring_water': 1}, {'can_opening': 0, 'pouring_water': 1},
                     {'cow': 0, 'crackling_fire': 1}, {'cow': 0, 'crackling_fire': 1},
                     {'crackling_fire': 0, 'fireworks': 1, 'footsteps': 2},
                     {'crackling_fire': 0, 'fireworks': 1, 'footsteps': 2},
                     {'crackling_fire': 0, 'fireworks': 1, 'footsteps': 2},
                     {'crackling_fire': 0, 'glass_breaking': 1, 'drinking_sipping': 2},
                     {'crackling_fire': 0, 'glass_breaking': 1, 'drinking_sipping': 2},
                     {'crackling_fire': 0, 'glass_breaking': 1, 'drinking_sipping': 2},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6},
                     {'water_drops': 0, 'crickets': 1, 'footsteps': 2, 'washing_machine': 3, 'helicopter': 4,
                      'crackling_fire': 5, 'wind': 6}, {'dog': 0, 'clock_tick': 1, 'clock_alarm': 2, 'water_drops': 3},
                     {'dog': 0, 'clock_tick': 1, 'clock_alarm': 2, 'water_drops': 3},
                     {'dog': 0, 'clock_tick': 1, 'clock_alarm': 2, 'water_drops': 3},
                     {'dog': 0, 'clock_tick': 1, 'clock_alarm': 2, 'water_drops': 3},
                     {'washing_machine': 0, 'sheep': 1}, {'washing_machine': 0, 'sheep': 1},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'can_opening': 0, 'engine': 1, 'airplane': 2, 'car_horn': 3, 'hand_saw': 4, 'church_bells': 5,
                      'brushing_teeth': 6, 'cat': 7, 'cow': 8, 'door_wood_creaks': 9, 'water_drops': 10, 'siren': 11,
                      'clock_tick': 12, 'insects': 13, 'washing_machine': 14, 'door_wood_knock': 15},
                     {'door_wood_creaks': 0, 'clock_alarm': 1}, {'door_wood_creaks': 0, 'clock_alarm': 1},
                     {'toilet_flush': 0, 'chainsaw': 1}, {'toilet_flush': 0, 'chainsaw': 1},
                     {'washing_machine': 0, 'vacuum_cleaner': 1, 'engine': 2},
                     {'washing_machine': 0, 'vacuum_cleaner': 1, 'engine': 2},
                     {'washing_machine': 0, 'vacuum_cleaner': 1, 'engine': 2},
                     {'door_wood_creaks': 0, 'footsteps': 1, 'door_wood_knock': 2, 'thunderstorm': 3, 'wind': 4},
                     {'door_wood_creaks': 0, 'footsteps': 1, 'door_wood_knock': 2, 'thunderstorm': 3, 'wind': 4},
                     {'door_wood_creaks': 0, 'footsteps': 1, 'door_wood_knock': 2, 'thunderstorm': 3, 'wind': 4},
                     {'door_wood_creaks': 0, 'footsteps': 1, 'door_wood_knock': 2, 'thunderstorm': 3, 'wind': 4},
                     {'door_wood_creaks': 0, 'footsteps': 1, 'door_wood_knock': 2, 'thunderstorm': 3, 'wind': 4},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'toilet_flush': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'coughing': 4, 'laughing': 5,
                      'wind': 6, 'pouring_water': 7},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'rain': 0, 'can_opening': 1, 'crickets': 2, 'clock_tick': 3, 'insects': 4, 'chirping_birds': 5,
                      'glass_breaking': 6},
                     {'engine': 0, 'chainsaw': 1, 'door_wood_creaks': 2, 'washing_machine': 3, 'crackling_fire': 4},
                     {'engine': 0, 'chainsaw': 1, 'door_wood_creaks': 2, 'washing_machine': 3, 'crackling_fire': 4},
                     {'engine': 0, 'chainsaw': 1, 'door_wood_creaks': 2, 'washing_machine': 3, 'crackling_fire': 4},
                     {'engine': 0, 'chainsaw': 1, 'door_wood_creaks': 2, 'washing_machine': 3, 'crackling_fire': 4},
                     {'engine': 0, 'chainsaw': 1, 'door_wood_creaks': 2, 'washing_machine': 3, 'crackling_fire': 4},
                     {'siren': 0, 'clapping': 1}, {'siren': 0, 'clapping': 1}, {'clock_tick': 0, 'breathing': 1},
                     {'clock_tick': 0, 'breathing': 1}, {'clock_alarm': 0, 'engine': 1, 'clock_tick': 2, 'chainsaw': 3},
                     {'clock_alarm': 0, 'engine': 1, 'clock_tick': 2, 'chainsaw': 3},
                     {'clock_alarm': 0, 'engine': 1, 'clock_tick': 2, 'chainsaw': 3},
                     {'clock_alarm': 0, 'engine': 1, 'clock_tick': 2, 'chainsaw': 3}, {'cat': 0, 'car_horn': 1},
                     {'cat': 0, 'car_horn': 1},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'dog': 0, 'crying_baby': 1, 'sea_waves': 2, 'door_wood_creaks': 3, 'crickets': 4, 'clock_tick': 5,
                      'helicopter': 6, 'mouse_click': 7, 'thunderstorm': 8, 'sneezing': 9, 'fireworks': 10,
                      'engine': 11, 'hand_saw': 12, 'cow': 13, 'clapping': 14, 'clock_alarm': 15, 'insects': 16,
                      'footsteps': 17, 'pig': 18, 'crackling_fire': 19, 'can_opening': 20, 'snoring': 21,
                      'brushing_teeth': 22, 'cat': 23, 'frog': 24, 'hen': 25, 'laughing': 26, 'chirping_birds': 27,
                      'door_wood_knock': 28, 'pouring_water': 29, 'rain': 30, 'car_horn': 31, 'keyboard_typing': 32,
                      'water_drops': 33, 'coughing': 34, 'siren': 35, 'sheep': 36, 'drinking_sipping': 37,
                      'breathing': 38, 'crow': 39, 'glass_breaking': 40, 'rooster': 41},
                     {'airplane': 0, 'sea_waves': 1, 'footsteps': 2, 'crackling_fire': 3, 'wind': 4},
                     {'airplane': 0, 'sea_waves': 1, 'footsteps': 2, 'crackling_fire': 3, 'wind': 4},
                     {'airplane': 0, 'sea_waves': 1, 'footsteps': 2, 'crackling_fire': 3, 'wind': 4},
                     {'airplane': 0, 'sea_waves': 1, 'footsteps': 2, 'crackling_fire': 3, 'wind': 4},
                     {'airplane': 0, 'sea_waves': 1, 'footsteps': 2, 'crackling_fire': 3, 'wind': 4},
                     {'pig': 0, 'hand_saw': 1, 'water_drops': 2}, {'pig': 0, 'hand_saw': 1, 'water_drops': 2},
                     {'pig': 0, 'hand_saw': 1, 'water_drops': 2}, {'brushing_teeth': 0, 'sea_waves': 1},
                     {'brushing_teeth': 0, 'sea_waves': 1}, {'frog': 0, 'pouring_water': 1, 'water_drops': 2},
                     {'frog': 0, 'pouring_water': 1, 'water_drops': 2},
                     {'frog': 0, 'pouring_water': 1, 'water_drops': 2},
                     {'washing_machine': 0, 'clapping': 1, 'drinking_sipping': 2},
                     {'washing_machine': 0, 'clapping': 1, 'drinking_sipping': 2},
                     {'washing_machine': 0, 'clapping': 1, 'drinking_sipping': 2}, {'brushing_teeth': 0, 'sneezing': 1},
                     {'brushing_teeth': 0, 'sneezing': 1}, {'clock_alarm': 0, 'siren': 1},
                     {'clock_alarm': 0, 'siren': 1}, {'brushing_teeth': 0, 'crickets': 1, 'insects': 2},
                     {'brushing_teeth': 0, 'crickets': 1, 'insects': 2},
                     {'brushing_teeth': 0, 'crickets': 1, 'insects': 2},
                     {'door_wood_knock': 0, 'keyboard_typing': 1, 'footsteps': 2, 'mouse_click': 3,
                      'crackling_fire': 4},
                     {'door_wood_knock': 0, 'keyboard_typing': 1, 'footsteps': 2, 'mouse_click': 3,
                      'crackling_fire': 4},
                     {'door_wood_knock': 0, 'keyboard_typing': 1, 'footsteps': 2, 'mouse_click': 3,
                      'crackling_fire': 4},
                     {'door_wood_knock': 0, 'keyboard_typing': 1, 'footsteps': 2, 'mouse_click': 3,
                      'crackling_fire': 4},
                     {'door_wood_knock': 0, 'keyboard_typing': 1, 'footsteps': 2, 'mouse_click': 3,
                      'crackling_fire': 4}, {'crickets': 0, 'chainsaw': 1}, {'crickets': 0, 'chainsaw': 1},
                     {'cow': 0, 'clock_alarm': 1, 'vacuum_cleaner': 2, 'siren': 3, 'crickets': 4, 'wind': 5},
                     {'cow': 0, 'clock_alarm': 1, 'vacuum_cleaner': 2, 'siren': 3, 'crickets': 4, 'wind': 5},
                     {'cow': 0, 'clock_alarm': 1, 'vacuum_cleaner': 2, 'siren': 3, 'crickets': 4, 'wind': 5},
                     {'cow': 0, 'clock_alarm': 1, 'vacuum_cleaner': 2, 'siren': 3, 'crickets': 4, 'wind': 5},
                     {'cow': 0, 'clock_alarm': 1, 'vacuum_cleaner': 2, 'siren': 3, 'crickets': 4, 'wind': 5},
                     {'cow': 0, 'clock_alarm': 1, 'vacuum_cleaner': 2, 'siren': 3, 'crickets': 4, 'wind': 5},
                     {'clapping': 0, 'sea_waves': 1}, {'clapping': 0, 'sea_waves': 1},
                     {'crackling_fire': 0, 'hand_saw': 1}, {'crackling_fire': 0, 'hand_saw': 1},
                     {'hand_saw': 0, 'thunderstorm': 1}, {'hand_saw': 0, 'thunderstorm': 1},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'sea_waves': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'crickets': 3, 'helicopter': 4,
                      'mouse_click': 5, 'engine': 6, 'airplane': 7, 'chainsaw': 8, 'hand_saw': 9, 'cow': 10,
                      'train': 11, 'washing_machine': 12, 'crackling_fire': 13, 'wind': 14, 'rain': 15, 'car_horn': 16,
                      'toilet_flush': 17, 'water_drops': 18, 'siren': 19, 'drinking_sipping': 20, 'breathing': 21},
                     {'crickets': 0, 'cow': 1}, {'crickets': 0, 'cow': 1},
                     {'door_wood_creaks': 0, 'insects': 1, 'crackling_fire': 2, 'footsteps': 3},
                     {'door_wood_creaks': 0, 'insects': 1, 'crackling_fire': 2, 'footsteps': 3},
                     {'door_wood_creaks': 0, 'insects': 1, 'crackling_fire': 2, 'footsteps': 3},
                     {'door_wood_creaks': 0, 'insects': 1, 'crackling_fire': 2, 'footsteps': 3},
                     {'clock_alarm': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'hand_saw': 3},
                     {'clock_alarm': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'hand_saw': 3},
                     {'clock_alarm': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'hand_saw': 3},
                     {'clock_alarm': 0, 'door_wood_creaks': 1, 'vacuum_cleaner': 2, 'hand_saw': 3},
                     {'crickets': 0, 'clapping': 1}, {'crickets': 0, 'clapping': 1},
                     {'mouse_click': 0, 'insects': 1, 'water_drops': 2},
                     {'mouse_click': 0, 'insects': 1, 'water_drops': 2},
                     {'mouse_click': 0, 'insects': 1, 'water_drops': 2}, {'breathing': 0, 'crackling_fire': 1},
                     {'breathing': 0, 'crackling_fire': 1}, {'crying_baby': 0, 'chirping_birds': 1},
                     {'crying_baby': 0, 'chirping_birds': 1}, {'brushing_teeth': 0, 'vacuum_cleaner': 1},
                     {'brushing_teeth': 0, 'vacuum_cleaner': 1}, {'crackling_fire': 0, 'footsteps': 1},
                     {'crackling_fire': 0, 'footsteps': 1}, {'airplane': 0, 'crow': 1, 'wind': 2},
                     {'airplane': 0, 'crow': 1, 'wind': 2}, {'airplane': 0, 'crow': 1, 'wind': 2},
                     {'siren': 0, 'crickets': 1}, {'siren': 0, 'crickets': 1}, {'breathing': 0, 'clapping': 1},
                     {'breathing': 0, 'clapping': 1}, {'siren': 0, 'mouse_click': 1, 'footsteps': 2},
                     {'siren': 0, 'mouse_click': 1, 'footsteps': 2}, {'siren': 0, 'mouse_click': 1, 'footsteps': 2},
                     {'door_wood_creaks': 0, 'crickets': 1, 'chirping_birds': 2},
                     {'door_wood_creaks': 0, 'crickets': 1, 'chirping_birds': 2},
                     {'door_wood_creaks': 0, 'crickets': 1, 'chirping_birds': 2},
                     {'cow': 0, 'hen': 1, 'sheep': 2, 'drinking_sipping': 3, 'pig': 4},
                     {'cow': 0, 'hen': 1, 'sheep': 2, 'drinking_sipping': 3, 'pig': 4},
                     {'cow': 0, 'hen': 1, 'sheep': 2, 'drinking_sipping': 3, 'pig': 4},
                     {'cow': 0, 'hen': 1, 'sheep': 2, 'drinking_sipping': 3, 'pig': 4},
                     {'cow': 0, 'hen': 1, 'sheep': 2, 'drinking_sipping': 3, 'pig': 4},
                     {'crying_baby': 0, 'brushing_teeth': 1, 'laughing': 2},
                     {'crying_baby': 0, 'brushing_teeth': 1, 'laughing': 2},
                     {'crying_baby': 0, 'brushing_teeth': 1, 'laughing': 2},
                     {'washing_machine': 0, 'train': 1, 'chirping_birds': 2, 'wind': 3},
                     {'washing_machine': 0, 'train': 1, 'chirping_birds': 2, 'wind': 3},
                     {'washing_machine': 0, 'train': 1, 'chirping_birds': 2, 'wind': 3},
                     {'washing_machine': 0, 'train': 1, 'chirping_birds': 2, 'wind': 3},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'cat': 2, 'wind': 3},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'cat': 2, 'wind': 3},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'cat': 2, 'wind': 3},
                     {'crying_baby': 0, 'door_wood_creaks': 1, 'cat': 2, 'wind': 3},
                     {'clock_alarm': 0, 'water_drops': 1}, {'clock_alarm': 0, 'water_drops': 1},
                     {'crying_baby': 0, 'crackling_fire': 1}, {'crying_baby': 0, 'crackling_fire': 1},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10},
                     {'can_opening': 0, 'door_wood_creaks': 1, 'brushing_teeth': 2, 'water_drops': 3, 'clock_tick': 4,
                      'footsteps': 5, 'laughing': 6, 'drinking_sipping': 7, 'washing_machine': 8, 'mouse_click': 9,
                      'crackling_fire': 10}, {'brushing_teeth': 0, 'snoring': 1, 'hand_saw': 2},
                     {'brushing_teeth': 0, 'snoring': 1, 'hand_saw': 2},
                     {'brushing_teeth': 0, 'snoring': 1, 'hand_saw': 2}, {'footsteps': 0, 'water_drops': 1},
                     {'footsteps': 0, 'water_drops': 1}, {'footsteps': 0}]

def classify_class(filename):
    embeddings , model_id, inferred_class = feature_extraction(filename=filename)
    model = tf.keras.models.load_model('models/sound_classifier' + str(model_id) + '.h5')
    predictions = model.predict(embeddings)
    predicted_class = np.argmax(predictions, axis=-1)
    print(predicted_class)
    res = statistics.mode(predicted_class)
    class_obj = model_classes[model_id]
    print(class_obj)
    class_ = list(class_obj.keys())[list(class_obj.values()).index(res)]
    return {
        "prediction" : inferred_class
    }

# print(classify_class('1-115920-B-22.wav'))